version: '3'
services:
  db:
    image: mysql:5.7-debian
    container_name: mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3307:3306"
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p ${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 5
    env_file:
      - .env
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kawa_product_app
    command: python manage.py migrate --noinput && python manage.py collectstatic --noinput && uvicorn kawa_product.asgi:application --host 127.0.0.1 --port 3001
    restart: always
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  data: